name: simple_dart_text_field
description: Text Field Component
version: 0.0.3
repository: https://github.com/simple-dart/text_field
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.2

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers:
